# Generated by Django 3.0.4 on 2020-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
