# Generated by Django 3.0.4 on 2020-03-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
    ]
